name: Generate Docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: npm run docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: amaribot-js/docs
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
          cname: amaribot.js.org
